require('config.keymap')
require('plugins.gruvbox')
require('plugins.nvim-treesitter')
require('plugins.telescope')
require('plugins.oil')
require('plugins.dressing')
require('plugins.formatting')
require('plugins.lsp')
